<?php if (isset($_GET['code'])){
  $code = "" . $_GET['code'];
  $other_bars = array(
    //L_Quiet
    "iVBORw0KGgoAAAANSUhEUgAAABsAAADxCAYAAAA6C8yxAAAABmJLR0QA/wD/AP+gvaeTAAAAvUlEQVR4nO3QOwrCUBAF0BtJGRsL97+TkMIF6B5cgOn9NAYHQbAwgeCZ6jLvcQ9M7q85l3wseSi5L/nw4f/Ucym7U5JssuDAYDAYbD5sX3IzN7b9pnOVZ4TBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMNjfYW2S3Q96umdXkoxJbm/v1yR5AJdDay0G/lBKAAAAAElFTkSuQmCC",
    //Start
    "iVBORw0KGgoAAAANSUhEUgAAAAoAAAD1CAYAAABp9mRxAAAABmJLR0QA/wD/AP+gvaeTAAAAYUlEQVRoge3KsQlCQRQAwUUs4GP/3diFXBMmFwnPRMXQzGQ2XKZqqjmO4z6v9t6396+uVad+DARBEARBEARBEARBEARBEARBEARBEARBEARBEAT/A8/VpWpmPnOt9W0eVU/B/hoeE+b8uQAAAABJRU5ErkJggg==",
    //Middle
    "iVBORw0KGgoAAAANSUhEUgAAAA8AAAD1CAYAAACP3681AAAABmJLR0QA/wD/AP+gvaeTAAAAh0lEQVRoge3LsQ3CMABE0QuiSZGGGbJXtmIUD0FHywyWrJRUpiGGGtr3q9NJL/1da21P0pP0eZ4fx19KuR//tm23/ul6yh/BMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDMAzDv3ZOckmSaZrGua7r2MuyjF1r/bbPFzZiL1Sn6Z00AAAAAElFTkSuQmCC",
    //End
    "iVBORw0KGgoAAAANSUhEUgAAAAoAAAD1CAYAAABp9mRxAAAABmJLR0QA/wD/AP+gvaeTAAAAYUlEQVRoge3KsQlCQRQAwUUs4GP/3diFXBMmFwnPRMXQzGQ2XKZqqjmO4z6v9t6396+uVad+DARBEARBEARBEARBEARBEARBEARBEARBEARBEAT/A8/VpWpmPnOt9W0eVU/B/hoeE+b8uQAAAABJRU5ErkJggg==",
    //R_Quiet
    "iVBORw0KGgoAAAANSUhEUgAAABsAAADxCAYAAAA6C8yxAAAABmJLR0QA/wD/AP+gvaeTAAAAvUlEQVR4nO3QOwrCUBAF0BtJGRsL97+TkMIF6B5cgOn9NAYHQbAwgeCZ6jLvcQ9M7q85l3wseSi5L/nw4f/Ucym7U5JssuDAYDAYbD5sX3IzN7b9pnOVZ4TBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMBgMBoPBYDAYDAaDwWAwGAwGg8FgMNjfYW2S3Q96umdXkoxJbm/v1yR5AJdDay0G/lBKAAAAAElFTkSuQmCC"
  );
  $l_bars = array(
    //L_0
    "iVBORw0KGgoAAAANSUhEUgAAABQAAADmCAYAAADV06UfAAAABmJLR0QA/wD/AP+gvaeTAAAAB3RJTUUH2wcHAxotbG66EgAAALNJREFUeJztzTFKxAAQheEfEXfvkMOl9DA5x+IxxNbO1jZVmoDNohbuNgnuAbb8Hgw8huGbLv/5uumfe1nX9aO6bPO+92ma3vabcRxf9/1Ddw4QCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBwLvksXre+t/Ng9/qqWqe55/qsO2/q2PVsizn6lQ1DMO5eqm6ApGPRWO10JLPAAAAAElFTkSuQmCC",
    //L_1
    "iVBORw0KGgoAAAANSUhEUgAAABQAAADmCAYAAADV06UfAAAABmJLR0QA/wD/AP+gvaeTAAAArklEQVR4nO3NMUoEURBF0YvY6h56cT+clYnLENPOTN2FHQyOgWPSH13AhOdBwaMoTnX9y+cs27Z9VNdj3mcfY2z/7t9mGWO8zpu7bhwgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgTfJfXU6+s98sCzLd/Vw7C/VY9W+71/V07E/V89V67qeq5eqX1nHQfT6moEiAAAAAElFTkSuQmCC",
    //L_2
    "iVBORw0KGgoAAAANSUhEUgAAABQAAADmCAYAAADV06UfAAAABmJLR0QA/wD/AP+gvaeTAAAAsElEQVR4nO3NIU7FYBSE0S+EAraqqutjA90SYRkEW4dlF5gXQFBM/8ACnjyjJjeTczv+8jHKvu/v1VEd8zy//dvso2zb9jo21cvoN105QCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKvktvq8ew/48E0Td/VXdW6rl/V/bn5rB6qlmW5VE/n/VI9V/0CSPY+vlapEhIAAAAASUVORK5CYII=",
    //L_3
    "iVBORw0KGgoAAAANSUhEUgAAABQAAADmCAYAAADV06UfAAAABmJLR0QA/wD/AP+gvaeTAAAAsUlEQVR4nO3NMUrEQACG0S+yqHfI4VJ6mJxDPIbYbmfrDVKFbRa1cG0SyAG2fD8MfAzMm27b1nW9VLftfB3689Dnved5/tjfTtP0vt8/dOcBgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCLzLTtVL1TAMf4cPfqvHrX+qp62/q+eqZVmu1WvVOI7X6q3qH36sMNIUi42HAAAAAElFTkSuQmCC",
    //L_4
    "iVBORw0KGgoAAAANSUhEUgAAABQAAADmCAYAAADV06UfAAAABmJLR0QA/wD/AP+gvaeTAAAAsklEQVR4nO3NsU3EABBE0W90AjpwJa6JBtwSogxEehkpTViXnABLmMQWFHDhm2i0Gr1t27Msy6Xaqm2apo/tL+//+vko8zy/Hfvq9eh33ThAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAm+SU/VUNQzDz/FgXdfv6n7ffFUPe/+sHqvGcbxWz/v9Wr1U/QKqqkIn6ZKb/QAAAABJRU5ErkJggg==",
    //L_5
    "iVBORw0KGgoAAAANSUhEUgAAABQAAADmCAYAAADV06UfAAAABmJLR0QA/wD/AP+gvaeTAAAAsElEQVR4nO3NMUrEABCF4T+yqG3qkLOl9GTiMcTWztZLhG0WtTA2Ce4BtvweDDyG4Zu2Peu6nqttn8+jj+P4sf3n/aq/HWVZltfj/q4bBwgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUDgTXKqnqqGYfi9evBT3VfN8/xdPez7r+px75fquWqapkv1UvUHVB4+7nXBQWAAAAAASUVORK5CYII=",
    //L_6
    "iVBORw0KGgoAAAANSUhEUgAAABQAAADmCAYAAADV06UfAAAABmJLR0QA/wD/AP+gvaeTAAAArUlEQVR4nO3NMUrEUBhG0RsZ1A1lTa5MXIbY2tnapk+YRtSAsUkgC5jyfNXl53Fe275lWa7VVm3jOH4e93meP4579X7qt1O/Hn3XjQcEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAg8Ca7VE9VwzD8HR+s6/pb3VdN0/RTPezvv6vHvb+q51O/VP0DHUc0CzLBhR8AAAAASUVORK5CYII=",
    //L_7
    "iVBORw0KGgoAAAANSUhEUgAAABQAAADmCAYAAADV06UfAAAABmJLR0QA/wD/AP+gvaeTAAAAB3RJTUUH2wcHAjIJDPKaXgAAALBJREFUeJztzbFNwwAURdFrFAEbeDyXLOCVEGMg2nS0LGHFRQQUhMaWPEDK86QvveLp/G5blmW5VLftvg79c+/TNJ33/TzPH4fN+94funOAQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBN4lp+qlahiGv8OD3+px6z/VU9W6rt/Vc9U4jtfqddtcq7eqf3lwMJw3mUT2AAAAAElFTkSuQmCC",
    //L_8
    "iVBORw0KGgoAAAANSUhEUgAAABQAAADmCAYAAADV06UfAAAABmJLR0QA/wD/AP+gvaeTAAAAB3RJTUUH2wcHAxcTGKHZ9AAAAK9JREFUeJztzTFKxAAURdEbGdQqkAVkfW4rjbgMsbWzdRNhmmG0cGwSyAKmPA8+vOJxfrct67qeq9t233ufpulr3yzL8nnYfBz6+94funOAQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBN4lp+qlahiGv8OD3+qxap7nn+qpahzHa/W8bS7V66G/Vf0DkdstnM7Rw/sAAAAASUVORK5CYII=",
    //L_9
    "iVBORw0KGgoAAAANSUhEUgAAABQAAADmCAYAAADV06UfAAAABmJLR0QA/wD/AP+gvaeTAAAAB3RJTUUH2wcHAxkdYZrZfQAAALJJREFUeJztzbFNwwAURdErhIANPJ5LFvBKKGOgtHS0tO4t4SKCFJgmVjJAyvOqp6ev89uu+b7pX3tZluWz2qptHMePfZ+m6bjv1fveH7pzgEAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCATeJY/V66X/3Tw4V09V8zz/Vs9V67r+VC9VwzCcqrfL/ak6VP0DjFNFLaLwx5cAAAAASUVORK5CYII=",
);
$r_bars = array(
  //R_0
  "iVBORw0KGgoAAAANSUhEUgAAABQAAADmCAYAAADV06UfAAAABmJLR0QA/wD/AP+gvaeTAAAAB3RJTUUH2wcHAxoXqmJjoAAAALNJREFUeJztzbFNwwAQheFfCAGtK1eeLwt4IDcRYyBaOlp6D0ATBYqExhYZIOX3pJOeTqfvqq7bfN/0r70Pw/B5/c/HXuZ5ft9vlmV52/cP3TlAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAu+Sx+qw9cvNg9/qqWqapp/qedufq5eqcRxP1bFqXddT9Vr1B4IgN+nUrYIBAAAAAElFTkSuQmCC",
  //R_1
  "iVBORw0KGgoAAAANSUhEUgAAABQAAADmCAYAAADV06UfAAAABmJLR0QA/wD/AP+gvaeTAAAAB3RJTUUH2wcHAxkdYZrZfQAAALBJREFUeJztzTFKBFEQRdGLiBr1bnpNbusn4jLE1GxS816AyaA2OCb90QVMeB4UPIriVNXlmI/Z13V9v/zlNMsY4+3f/evsY4yXeXPTlQMEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAg8Cq5rR6P/jMf7Pv+Xd0d+6/qvmpZls/q4difq6eqbdvO1XPVLwH3O1iVEfBXAAAAAElFTkSuQmCC",
  //R_2
  "iVBORw0KGgoAAAANSUhEUgAAABQAAADmCAYAAADV06UfAAAABmJLR0QA/wD/AP+gvaeTAAAAB3RJTUUH2wcHAxkdYZrZfQAAALJJREFUeJztzTFKxAAQheEfEfVCOZOHyTkWjyG2drbbpkoT2GZRA8YmQQ+w5fdg4DEM31Rt+1yOPgzDeduzLMvHv5v3o4/j+Lb95fUod904QCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAJvkvvqee8/x4N1Xb+rh6ppmr6qx/3ms3qqmuf5Wp32/bV6qfoFWsg+jjMCy7YAAAAASUVORK5CYII=",
  //R_3
  "iVBORw0KGgoAAAANSUhEUgAAABQAAADmCAYAAADV06UfAAAABmJLR0QA/wD/AP+gvaeTAAAAB3RJTUUH2wcHAxkdYZrZfQAAALBJREFUeJztzSFOxFAYRtEbQgZkXZfIBrqgGsIyCBaHxXcBYyaA4GGmoQsYeT5185L/vKpRjWmazuN/n4f+OPT7HsuyvO2367q+7u933XhAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAm+y++qpaozxe/jgpzpd+7t6uPZX9Vg1z/Oleq7atu1SvVT9Ad0DTHqkGHR6AAAAAElFTkSuQmCC",
  //R_4
  "iVBORw0KGgoAAAANSUhEUgAAABQAAADmCAYAAADV06UfAAAABmJLR0QA/wD/AP+gvaeTAAAAB3RJTUUH2wcHAxk6xJBsFgAAAK9JREFUeJztzbFNw2AUhdFPEQ6U3pJhPEfEGIjWHS0buKSJIAU/jS0YIOW51dXV03lVoxrzPH+OPeu6fhx79f6vr0dfluVt/OX1KKfuHCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBd8lD9Vw1xvg5HkzTdKvO+8139bj3r+qpatu2a3XZ92v1UvULQRQ7JcUkAzwAAAAASUVORK5CYII=",
  //R_5
  "iVBORw0KGgoAAAANSUhEUgAAABQAAADmCAYAAADV06UfAAAABmJLR0QA/wD/AP+gvaeTAAAAr0lEQVR4nO3NMUoDYRSF0Q8RtZxduq1pJMsQWztb22HaAZtgUuS3yWAWkPLc6vK4nFc1qjFN08/4z/detm372jfV503/2Ps8z+/7/qE7BwgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUDgXfJYvVaNMS43D87VU9WyLKfq+Xr/rV6u/Vi9Va3reqwOVX9PoD5eXsysyQAAAABJRU5ErkJggg==",
  //R_6
  "iVBORw0KGgoAAAANSUhEUgAAABQAAADmCAYAAADV06UfAAAABmJLR0QA/wD/AP+gvaeTAAAAB3RJTUUH2wcHAxk6xJBsFgAAAKtJREFUeJztzbFNxEAURdErhIHQLsD1URmiDETqjJQuSNAuAUNiCxew4XnR1ejrTNWoxjzPX2Pftm2fx/uyLB/jf9up30/9dsRdNx4QCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBwJvsvnquGmP8Hh9M0/RTPVSt63qtHvf7S/W093f1curXqj8WhklBDlbYDwAAAABJRU5ErkJggg==",
  //R_7
  "iVBORw0KGgoAAAANSUhEUgAAABQAAADmCAYAAADV06UfAAAABmJLR0QA/wD/AP+gvaeTAAAAr0lEQVR4nO3NIU7EYACE0S+ELKimt+QwvUQN4RgEi8Nyg8o1G0DwY7ahB1j5Ro2YvKka1Zjn+Tz+83noH3tZ1/V93y/L8nbYvO7lrhsHCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQOBNcl89VY0xfg8HP9Xp2r+rh6ppmr6qx6pt2y7V83VzqV6q/gAqTkywn2+SsgAAAABJRU5ErkJggg==",
  //R_8
  "iVBORw0KGgoAAAANSUhEUgAAABQAAADmCAYAAADV06UfAAAABmJLR0QA/wD/AP+gvaeTAAAAq0lEQVR4nO3NIU7EYACE0S+EsMjesJKTbfYYBIvDYuubULEBBD+Ghh5g5Rs1YvKmalRjmqaP8Z/3vazr+rZv5nl+PWxeDv15L3fdOEAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCb5L76qlqjPFzOPiuHqqWZfmqTlXbtn1Wj3+ba3U+9EvVL1njT7BSwSznAAAAAElFTkSuQmCC",
  //R_9
  "iVBORw0KGgoAAAANSUhEUgAAABQAAADmCAYAAADV06UfAAAABmJLR0QA/wD/AP+gvaeTAAAAs0lEQVR4nO3NMUrEABCF4R+R1SqQA+R8HiaXSCMeQ2ztbL1Bym0WtTA2Ce4BtvweDDyG4ZuqbZ/zVf88+jiOH9ueZVnej/08z2/bf16PcteNAwQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCDwJrmvnvb+e/XgpzpVTdP0XT1UDcPwVT1Wret6qZ73+0v1UvUHz1w4H4eBxboAAAAASUVORK5CYII=",
 );
  if (strlen($code) == 12){
    echo "<style>td{border-style: none;border-width: thin;}</style>";
    echo "<table cellspacing=\"0\" cellpadding=\"0\" style=\"border-collapse:collapse; border-style:solid; border-none;\">";
    $hexEncoderBegin="<td><img src=\"data:image/png;base64,";
    $hexEncoderEnd= "\"></td>";
    echo "<tr style=\"border-collapse:collapse; border-style:solid;\">";
    echo $hexEncoderBegin . $other_bars[0] . $hexEncoderEnd;
    echo $hexEncoderBegin . $other_bars[1] . $hexEncoderEnd;
    echo $hexEncoderBegin . $l_bars[$code[0]] . $hexEncoderEnd;
    echo $hexEncoderBegin . $l_bars[$code[1]] . $hexEncoderEnd;
    echo $hexEncoderBegin . $l_bars[$code[2]] . $hexEncoderEnd;
    echo $hexEncoderBegin . $l_bars[$code[3]] . $hexEncoderEnd;
    echo $hexEncoderBegin . $l_bars[$code[4]] . $hexEncoderEnd;
    echo $hexEncoderBegin . $l_bars[$code[5]] . $hexEncoderEnd;
    echo $hexEncoderBegin . $other_bars[2] . $hexEncoderEnd;
    echo $hexEncoderBegin . $r_bars[$code[6]] . $hexEncoderEnd;
    echo $hexEncoderBegin . $r_bars[$code[7]] . $hexEncoderEnd;
    echo $hexEncoderBegin . $r_bars[$code[8]] . $hexEncoderEnd;
    echo $hexEncoderBegin . $r_bars[$code[9]] . $hexEncoderEnd;
    echo $hexEncoderBegin . $r_bars[$code[10]] . $hexEncoderEnd;
    echo $hexEncoderBegin . $r_bars[$code[11]] . $hexEncoderEnd;
    echo $hexEncoderBegin . $other_bars[3] . $hexEncoderEnd;
    echo $hexEncoderBegin . $other_bars[4] . $hexEncoderEnd;
    echo "</tr>";
   echo "<tr style=\"border-collapse:collapse; border-style:none;\">";
   echo "<td></td>";
   echo "<td>$code[0]</td>";
   echo "<td></td>";
   echo "<td>$code[1]</td>";
   echo "<td>$code[2]</td>";
   echo "<td>$code[3]</td>";
   echo "<td>$code[4]</td>";
   echo "<td>$code[5]</td>";
   echo "<td></td>";
   echo "<td>$code[6]</td>";
   echo "<td>$code[7]</td>";
   echo "<td>$code[8]</td>";
   echo "<td>$code[9]</td>";
   echo "<td>$code[10]</td>";
   echo "<td></td>";
   echo "<td>$code[11]</td>";
   echo "<td></td>";
   echo "</tr>";
    echo "</table>";

  }else{
    echo "Invalid Parameter Value";
  }

}else{
  echo "No Parameter Given";
} ?>
